DROP TABLE role IF EXISTS;
DROP TABLE vote IF EXISTS;
DROP TABLE user IF EXISTS;

DROP TABLE restaurant IF EXISTS;
DROP TABLE lunch IF EXISTS;
DROP TABLE dish IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS BIGINT START WITH 100000000;

CREATE TABLE user
(
  id               BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
);

CREATE UNIQUE INDEX users_unique_email_idx
  ON USER (email);

CREATE TABLE role
(
  user_id BIGINT NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_role_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE
);

CREATE TABLE vote
(
  id            BIGINT NOT NULL,
  daate_time    TIMESTAMP NOT NULL,
  user_id       BIGINT NOT NULL,
  CONSTRAINT user_id_idx UNIQUE (user_id, daate_time),
  FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX vote_unique_idx
    ON VOTE (user_id, daate_time);

CREATE TABLE restaurant
(
    id            BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name          VARCHAR(255)  NOT NULL,
);

CREATE TABLE lunch
(
  id            BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name          VARCHAR(255)    NOT NULL,
  date          DATE            NOT NULL,
  restaurant_id BIGINT         NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES RESTAURANT (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX lunch_unique_date_restaurant_id_idx
    ON LUNCH (restaurant_id, date);

CREATE TABLE dish
(
  id            BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name          VARCHAR(255)    NOT NULL,
  price         DECIMAL(10,2)   NOT NULL,
  lunch_id      BIGINT         NOT NULL,
  FOREIGN KEY (lunch_id) REFERENCES LUNCH (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX dish_unique_name_lunch_id_idx
    ON DISH (lunch_id, name);